-- MySQL Script generated by MySQL Workbench
-- Wed Jun 13 15:24:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fastcloud
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fastcloud
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fastcloud` DEFAULT CHARACTER SET utf8 ;
USE `fastcloud` ;

-- -----------------------------------------------------
-- Table `fastcloud`.`sys_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fastcloud`.`sys_user` (
  `user_id` BIGINT(64) NOT NULL,
  `username` VARCHAR(64) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `phone` VARCHAR(32) NULL,
  `email` VARCHAR(64) NULL,
  `nickname` VARCHAR(64) NULL,
  `image` VARCHAR(64) NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `status` INT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastcloud`.`sys_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fastcloud`.`sys_role` (
  `role_id` BIGINT(64) NOT NULL,
  `name` VARCHAR(32) NULL COMMENT '名称',
  `icon` VARCHAR(64) NULL,
  `description` VARCHAR(128) NULL,
  `status` INT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastcloud`.`sys_user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fastcloud`.`sys_user_role` (
  `user_role_id` BIGINT(64) NOT NULL,
  `user_id` BIGINT(64) NOT NULL,
  `role_id` BIGINT(64) NOT NULL,
  INDEX `fk_sys_user_has_sys_role_sys_role1_idx` (`role_id` ASC),
  INDEX `fk_sys_user_has_sys_role_sys_user_idx` (`user_id` ASC),
  PRIMARY KEY (`user_role_id`),
  CONSTRAINT `fk_sys_user_has_sys_role_sys_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `fastcloud`.`sys_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_user_has_sys_role_sys_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `fastcloud`.`sys_role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastcloud`.`sys_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fastcloud`.`sys_permission` (
  `permission_id` BIGINT(64) NOT NULL,
  `parent_id` BIGINT(64) NULL COMMENT '父权限（可能会使用不到，默认为0）',
  `name` VARCHAR(32) NULL,
  `services` VARCHAR(256) NULL COMMENT '该权限能够使用的服务。如：auth-service;hello-service（服务之间用分号隔开）',
  `description` VARCHAR(128) NULL,
  `status` INT NULL,
  PRIMARY KEY (`permission_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastcloud`.`sys_role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fastcloud`.`sys_role_permission` (
  `role_permission_id` BIGINT(64) NULL,
  `role_id` BIGINT(64) NOT NULL,
  `permission_id` BIGINT(64) NOT NULL,
  INDEX `fk_sys_role_has_sys_permission_sys_permission1_idx` (`permission_id` ASC),
  INDEX `fk_sys_role_has_sys_permission_sys_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_sys_role_has_sys_permission_sys_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `fastcloud`.`sys_role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_role_has_sys_permission_sys_permission1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `fastcloud`.`sys_permission` (`permission_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastcloud`.`sys_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fastcloud`.`sys_menu` (
  `menu_id` BIGINT(64) NOT NULL,
  `parent_id` BIGINT(64) NULL,
  `name` VARCHAR(32) NULL,
  `url` VARCHAR(128) NULL,
  `perms` VARCHAR(128) NULL COMMENT '授权(多个用逗号分隔，如：user:list,user:create)\n',
  `type` INT NULL,
  `icon` VARCHAR(64) NULL,
  `orderNum` INT NULL COMMENT '排序',
  `status` INT NULL,
  PRIMARY KEY (`menu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastcloud`.`sys_permission_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fastcloud`.`sys_permission_menu` (
  `sys_permission_menu_id` BIGINT(64) NOT NULL,
  `permission_id` BIGINT(64) NOT NULL,
  `menu_id` BIGINT(64) NOT NULL,
  INDEX `fk_sys_permission_has_sys_menu_sys_menu1_idx` (`menu_id` ASC),
  INDEX `fk_sys_permission_has_sys_menu_sys_permission1_idx` (`permission_id` ASC),
  PRIMARY KEY (`sys_permission_menu_id`),
  CONSTRAINT `fk_sys_permission_has_sys_menu_sys_permission1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `fastcloud`.`sys_permission` (`permission_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_permission_has_sys_menu_sys_menu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `fastcloud`.`sys_menu` (`menu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastcloud`.`sys_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fastcloud`.`sys_token` (
  `user_id` BIGINT(64) NOT NULL,
  `token` VARCHAR(128) NOT NULL,
  `expire_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  INDEX `fk_sys_token_sys_user1_idx` (`user_id` ASC),
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_sys_token_sys_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fastcloud`.`sys_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastcloud`.`sys_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fastcloud`.`sys_log` (
  `log_id` BIGINT(64) NOT NULL,
  `username` VARCHAR(64) NULL COMMENT '用户名',
  `operation` VARCHAR(64) NULL COMMENT '操作',
  `method` VARCHAR(32) NULL COMMENT '请求方法',
  `params` VARCHAR(128) NULL COMMENT '请求参数',
  `time` BIGINT(64) NULL COMMENT '执行时长',
  `ip` VARCHAR(64) NULL COMMENT 'IP地址',
  `create_time` DATETIME NULL,
  PRIMARY KEY (`log_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
