spring:
  application:
    name: auth-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/fastcloud?characterEncoding=utf8&useSSL=false&tinyInt1isBit=false&autoReconnect=true
    username: root
    password: rootroot

server:
  port: 8082

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*/*.xml
  typeAliasesPackage: com.fastcloud.cn.support.domain.*
  global-config:
    id-type: 2
    field-strategy: 2
    auto-set-db-type: true
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/