spring:
  application:
    name: auth-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/fastcloud?characterEncoding=utf8&useSSL=false&tinyInt1isBit=false&autoReconnect=true
    username: root
    password: rootroot
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        min-idle: 0
        max-idle: 8

server:
  port: 8080

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*/*.xml
  typeAliasesPackage: com.fastcloud.cn.support.domain.*
  global-config:
    id-type: 2
    field-strategy: 2
    auto-set-db-type: true
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

merryyou:
  security:
    oauth2:
      storeType: jwt #或者jwt
      jwtSigningKey: merryyou
      clients[0]:
        clientId: merryyou
        clientSecret: merryyou
      clients[1]:
        clientId: merryyou1
        clientSecret: merryyou1

logging:
  level:
    org.springframework: debug

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/


